Resources:
 TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: TestVPC

    MyInternetGateway:
     Type: AWS::EC2::InternetGateway
     Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway
